### ISSUE TITLE
Not running ? What is the issue

### ISSUE THREAD

**Issue by subaru471171** [marcussacana/SacanaWrapper#27]
C:\Users\arkad\OneDrive\Downloads\SacanaWrapper>StringTool -Dump 01_comn_11.ast 01_comn_11.txt
1 Tasks to be Executed.
Dumping: 01_comn_11.ast
System.IO.FileLoadException: Could not load file or assembly 'Microsoft.CodeAnalysis, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'Microsoft.CodeAnalysis, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at DotNetVM.InitializeEngine(String[] Lines, String FileName, String SourcePath)
   at DotNetVM..ctor(String[] SourceFiles, String FileName) in C:\projects\sacanawrapper\SacanaWrapper\DNVM.cs:line 48
   at SacanaWrapper.Wrapper.TryImport(String Plugin, Byte[] Script) in C:\projects\sacanawrapper\SacanaWrapper\Wrapper.cs:line 226
   at SacanaWrapper.Wrapper.Import(Byte[] Script, String Extension, Boolean PreventCorrupt, Boolean TryLastPluginFirst) in C:\projects\sacanawrapper\SacanaWrapper\Wrapper.cs:line 97
   at SacanaWrapper.Wrapper.Import(String ScriptPath, Boolean PreventCorrupt, Boolean TryLastPluginFirst) in C:\projects\sacanawrapper\SacanaWrapper\Wrapper.cs:line 46
   at StringTool.Program.Main(String[] Args) in C:\projects\sacanawrapper\StringTool\Program.cs:line 282

**Comment by marcussacana** [comment]
this issue is pretty annoying, basically some missing libraries from .net, usually are present if you install visual studio completly.
try extract this files to the tool directory:
[dlls.7z](https://github.com/user-attachments/files/17573407/dlls.zip)
